version: '3.8'

services:

    order:
        build: OnlineFashionHome-1
        ports:
        - 8001:8001



    postgres:
        image: postgres:14.5
        ports:
        - '5432:5432'

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Dharani0509
            POSTGRES_DB: ocdb

